[gettext] fix compilation on ubuntu systems
This patch fixed the following error:

gcc -std=gnu99
-DLOCALEDIR=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/share/locale\"
-DBISON_L
OCALEDIR=\"/usr/share/locale\"
-DLOCALE_ALIAS_PATH=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/s
hare/locale\" -DUSEJEXE=0
-DGETTEXTJEXEDIR=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/lib/gette
xt\"
-DGETTEXTJAR=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/share/gettext/gettext.jar\"
-DLIBD
IR=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/lib\"
-DGETTEXTDATADIR=\"/home/frogger/pengutroni
x/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/share/gettext\"
-DPROJECTSDIR=\"/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengu
tronix-AllYes-trunk/platform-ARM-reference/sysroot-host/share/gettext/projects\"
-DHAVE_CONFIG_H -I. -I.. -I. -I. -I.. -I.. -I../libgrep -I../gnulib-lib
-I.
./gnulib-lib -I../intl -I../../gettext-runtime/intl
-I/home/frogger/pengutronix/bsp/OSELAS.BSP-Pengutronix-AllYes-trunk/platform-ARM-reference/sysroot-host/
include -g -O2 -c write-catalog.c  -fPIC -DPIC -o .libs/write-catalog.o
In function 'open',
    inlined from 'msgdomain_list_print' at write-catalog.c:223:
/usr/include/bits/fcntl2.h:51: error: call to '__open_missing_mode'
declared with attribute error: open with O_CREAT in second argument
needs 3 arguments

Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
(cherry picked from commit 895a9179a9ba6db0bec85361613e5c2b4e86b054)

Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>